import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import Provider from "@/Components/Provider/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0 w-full`}
      >
        <main className="w-full min-h-screen">
          <Provider>
            {/* Header with container */}
            <div className="max-w-6xl mx-auto px-4 w-full">
              <Header />
            </div>
            
            {/* Main content - full width to eliminate white lines */}
            <div className="w-full">
              {children}
            </div>
            
            {/* Footer - full width */}
            <Footer/>
          </Provider>
        </main>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "../Components/Header/Header";
// import Footer from "@/Components/Footer/Footer";
// import Provider from "@/Components/Provider/Provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <main>
//           <Provider>
//             <div className="max-w-6xl mx-auto px-4 w-full"> {/* Consistent container */}
//               <Header />
//               <div className="pt-0 "> {/* Add this wrapper */}
//               {children}
//               </div>
//             </div>
//             <Footer/>
//           </Provider>
//         </main>
//       </body>
//     </html>
//   );
// }
